from .adapters import StorageAdapter
from .codec import ENVELOPE_MAGIC, decode_envelope, encode_envelope
from .errors import (
    AdapterUnavailableError,
    AlreadyExistsError,
    InvalidContentTypeError,
    InvalidKeyError,
    InvalidNamespaceError,
    NotFoundError,
    PayloadTooLargeError,
    StorageBackendError,
    StorageConfigurationError,
    StorageError,
    StorageTimeoutError,
    UnknownNamespaceError,
    UnsupportedOperationError,
)
from .models import StorageAck, StorageObject, StorageObjectSummary, StoragePage
from .routing import RouteResolution, StorageRouteResolver
from .validation import (
    normalize_page_size,
    validate_content_type,
    validate_key,
    validate_metadata,
    validate_namespace,
    validate_payload,
    validate_storage_write,
    validate_ttl,
)

__all__ = [
    "AdapterUnavailableError",
    "AlreadyExistsError",
    "ENVELOPE_MAGIC",
    "InvalidContentTypeError",
    "InvalidKeyError",
    "InvalidNamespaceError",
    "NotFoundError",
    "PayloadTooLargeError",
    "RouteResolution",
    "StorageAck",
    "StorageAdapter",
    "StorageBackendError",
    "StorageConfigurationError",
    "StorageError",
    "StorageObject",
    "StorageObjectSummary",
    "StoragePage",
    "StorageRouteResolver",
    "StorageTimeoutError",
    "UnknownNamespaceError",
    "UnsupportedOperationError",
    "decode_envelope",
    "encode_envelope",
    "normalize_page_size",
    "validate_content_type",
    "validate_key",
    "validate_metadata",
    "validate_namespace",
    "validate_payload",
    "validate_storage_write",
    "validate_ttl",
]
