from .adapters import StorageAdapter
from .codec import ENVELOPE_MAGIC, decode_envelope, encode_envelope
from .errors import (
    AdapterUnavailableError,
    AlreadyExistsError,
    InvalidContentTypeError,
    InvalidKeyError,
    InvalidNamespaceError,
    NotFoundError,
    PayloadTooLargeError,
    StorageBackendError,
    StorageConfigurationError,
    StorageError,
    StorageTimeoutError,
    UnknownNamespaceError,
    UnsupportedOperationError,
)
from .facade import (
    StorageFacade,
    StorageMetricsHook,
    configure_storage,
    create,
    delete,
    exists,
    get,
    get_storage_facade,
    list,
    put,
)
from .lifecycle import ManagedAdapter, StorageLifecycleManager
from .models import StorageAck, StorageObject, StorageObjectSummary, StoragePage
from .routing import RouteResolution, StorageRouteResolver
from .settings import (
    AdapterSettings,
    MySQLAdapterSettings,
    NASAdapterSettings,
    RedisAdapterSettings,
    S3AdapterSettings,
    StorageSettings,
)
from .validation import (
    normalize_page_size,
    validate_content_type,
    validate_key,
    validate_metadata,
    validate_namespace,
    validate_payload,
    validate_storage_write,
    validate_ttl,
)

__all__ = [
    "AdapterUnavailableError",
    "AlreadyExistsError",
    "AdapterSettings",
    "ENVELOPE_MAGIC",
    "InvalidContentTypeError",
    "InvalidKeyError",
    "InvalidNamespaceError",
    "ManagedAdapter",
    "MySQLAdapterSettings",
    "NASAdapterSettings",
    "NotFoundError",
    "PayloadTooLargeError",
    "RedisAdapterSettings",
    "RouteResolution",
    "S3AdapterSettings",
    "StorageAck",
    "StorageAdapter",
    "StorageBackendError",
    "StorageConfigurationError",
    "StorageError",
    "StorageFacade",
    "StorageLifecycleManager",
    "StorageMetricsHook",
    "StorageObject",
    "StorageObjectSummary",
    "StoragePage",
    "StorageRouteResolver",
    "StorageSettings",
    "StorageTimeoutError",
    "UnknownNamespaceError",
    "UnsupportedOperationError",
    "configure_storage",
    "create",
    "decode_envelope",
    "delete",
    "encode_envelope",
    "exists",
    "get",
    "get_storage_facade",
    "list",
    "normalize_page_size",
    "put",
    "validate_content_type",
    "validate_key",
    "validate_metadata",
    "validate_namespace",
    "validate_payload",
    "validate_storage_write",
    "validate_ttl",
]
